# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Position Controllers ---------------------------------------
rail_to_shaft_position_controller:
  type: position_controllers/JointPositionController
  joint: rail_to_shaft_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

shaft_to_arm0_position_controller:
  type: position_controllers/JointPositionController
  joint: shaft_to_arm0_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

arm0_to_arm1_position_controller:
  type: position_controllers/JointPositionController
  joint: arm0_to_arm1_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

arm1_to_arm2_position_controller:
  type: position_controllers/JointPositionController
  joint: arm1_to_arm2_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

arm2_to_effector_base_position_controller:
  type: position_controllers/JointPositionController
  joint: arm2_to_effector_base_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

effector_base_to_effector_end_position_controller:
  type: effector_base_to_effector_end_joint
  joint: rail_to_shaft_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
