<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="arcsys2">

  <material name="white"> <color rgba="${255/255} ${255/255} ${255/255} 1.0" /> </material>
  <material name="red">   <color rgba="${255/255} ${  0/255} ${  0/255} 1.0" /> </material>
  <material name="green"> <color rgba="${  0/255} ${255/255} ${  0/255} 1.0" /> </material>
  <material name="blue">  <color rgba="${  0/255} ${  0/255} ${255/255} 1.0" /> </material>


  <xacro:property name="pi" value="3.1415"/>

  <xacro:property name="shaft_height" value="2.0"/>
  <xacro:property name="shaft_thickness" value="0.1"/>

  <xacro:property name="arm_width" value="0.1"/>
  <xacro:property name="arm_height" value="${arm_width}"/>

  <xacro:property name="arm0_length" value="0.1"/>
  <xacro:property name="arm1_length" value="0.5"/>
  <xacro:property name="arm2_length" value="0.5"/>


  <xacro:LINK name="world">
    <origin xyz="0 0 0" />
  </xacro:LINK>

  <xacro:JOINT parent="world" child="shaft" type="prismatic" y="1" lower="-5.0" upper="5.0">
    <origin xyz="0 0 ${shaft_height/2}" rpy="0 0 0" />
  </xacro:JOINT>

  <xacro:LINK name="shaft" width="${shaft_thickness}" length="${shaft_thickness}" height="${shaft_height}" color="red">
    <origin xyz="0 0 0" />
  </xacro:LINK>

  <xacro:JOINT parent="shaft" child="arm0" type="prismatic" z="1" lower="-0.5" upper="0.5">
    <origin xyz="${shaft_thickness/2 + arm0_length/2} 0 ${shaft_height/4}" rpy="0 0 0"/>
  </xacro:JOINT>

  <xacro:LINK name="arm0" width="${arm_width}" length="${arm0_length}" height="${arm_height}" color="green">
    <origin xyz="0 0 0"/>
  </xacro:LINK>

  <xacro:JOINT parent="arm0" child="arm1" type="revolute" z="1">
    <origin xyz="${arm0_length/2} 0 0" rpy="0 0 0"/>
  </xacro:JOINT>

  <xacro:LINK name="arm1" width="${arm_width}" length="${arm1_length}" height="${arm_height}" color="blue">
    <origin xyz="${arm1_length/2} 0 0" />
  </xacro:LINK>

  <xacro:JOINT parent="arm1" child="arm2" type="revolute" z="1">
    <origin xyz="${arm1_length} 0 0" rpy="0 0 0"/>
  </xacro:JOINT>

  <xacro:LINK name="arm2" width="${arm_width}" length="${arm2_length}" height="${arm_height}" color="red">
    <origin xyz="${arm2_length/2} 0 0" />
  </xacro:LINK>


  <xacro:macro name="LINK" params="name width:=0 length:=0 height:=0 color:=white *origin">
    <link name="${name}">
      <visual>
        <xacro:insert_block name="origin"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
    </link>
  </xacro:macro>

  <xacro:macro name="JOINT" params="parent child type x:=0 y:=0 z:=0 lower:=${-pi/2} upper:=${pi/2} *origin">
    <joint name="${parent}->${child}" type="${type}">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${x} ${y} ${z}"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>
  </xacro:macro>

</robot>
