<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="arcsys2">

  <material name="white"> <color rgba="${255/255} ${255/255} ${255/255} 1.0" /> </material>
  <material name="red">   <color rgba="${255/255} ${  0/255} ${  0/255} 1.0" /> </material>
  <material name="green"> <color rgba="${  0/255} ${255/255} ${  0/255} 1.0" /> </material>
  <material name="blue">  <color rgba="${  0/255} ${  0/255} ${255/255} 1.0" /> </material>


  <xacro:property name="pi" value="3.1415"/>

  <xacro:property name="shaft_height" value="2.0"/>
  <xacro:property name="shaft_thickness" value="0.1"/>

  <xacro:property name="arm_width" value="0.1"/>
  <xacro:property name="arm_height" value="${arm_width}"/>

  <xacro:property name="arm0_length" value="0.1"/>
  <xacro:property name="arm1_length" value="0.5"/>
  <xacro:property name="arm2_length" value="0.5"/>


  <xacro:PLAIN_LINK name="world"/>

  <xacro:JOINT name="world->shaft" type="prismatic" y="1" lower="-5.0" upper="5.0">
    <origin xyz="0 0 ${shaft_height/2}"/>
  </xacro:JOINT>

  <xacro:PLAIN_LINK name="shaft" length="${shaft_thickness}" width="${shaft_thickness}" height="${shaft_height}" color="red"/>

  <xacro:JOINT name="shaft->arm0" type="prismatic" z="1" lower="-0.5" upper="0.5">
    <origin xyz="${shaft_thickness/2} 0 ${shaft_height/4}"/>
  </xacro:JOINT>

  <xacro:SCARA_LINK name="arm0" width="${arm_width}" length="${arm0_length}" height="${arm_height}" color="green"/>

  <xacro:SCARA_JOINT name="arm0->arm1" parent_length="${arm0_length}"/>

  <xacro:SCARA_LINK name="arm1" width="${arm_width}" length="${arm1_length}" height="${arm_height}" color="blue"/>

  <xacro:SCARA_JOINT name="arm1->arm2" parent_length="${arm1_length}"/>

  <xacro:SCARA_LINK name="arm2" width="${arm_width}" length="${arm2_length}" height="${arm_height}" color="red"/>


  <xacro:macro name="PLAIN_LINK" params="name width:=0 length:=0 height:=0 color:=white">
    <link name="${name}">
      <origin xyz="0 0 0"/>
      <visual>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
    </link>
  </xacro:macro>

  <xacro:macro name="SCARA_LINK" params="name width:=0 length:=0 height:=0 color:=white">
    <link name="${name}">
      <visual>
        <origin xyz="${length/2} 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
    </link>
  </xacro:macro>

  <xacro:macro name="JOINT" params="name type x:=0 y:=0 z:=0 lower:=${-pi/2} upper:=${pi/2} *origin">
    <joint name="${name}" type="${type}">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${x} ${y} ${z}"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="SCARA_JOINT" params="parent_length lower:=${-pi/2} upper:=${pi/2}">
    <joint name="${name}" type="revolute">
      <origin xyz="${parent_length} 0 0"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>
  </xacro:macro>

</robot>
