<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="arcsys2">

  <material name="white"> <color rgba="${255/255} ${255/255} ${255/255} 1.0"/> </material>
  <material name="red">   <color rgba="${255/255} ${  0/255} ${  0/255} 1.0"/> </material>
  <material name="green"> <color rgba="${  0/255} ${255/255} ${  0/255} 1.0"/> </material>
  <material name="blue">  <color rgba="${  0/255} ${  0/255} ${255/255} 1.0"/> </material>


  <xacro:LINK name="world">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:LINK>

  <xacro:FIXED_JOINT parent="world" child="rail"/>

  <xacro:property name="rail_height" value="0.1"/>
  <xacro:LINK name="rail" width="10.0" depth="0.3" height="${rail_height}" color="blue">
    <origin xyz="0 0 ${rail_height/2}" rpy="0 0 0"/>
  </xacro:LINK>

  <xacro:PRISMATIC_JOINT parent="rail" child="base" x="1" lower="-5.0" upper="5.0"/>

  <xacro:property name="base_height" value="2.0"/>
  <xacro:LINK name="base" width="0.1" depth="0.1" height="${base_height}" color="red">
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </xacro:LINK>

  <xacro:PRISMATIC_JOINT parent="base" child="arm0" z="1" lower="-0.5" upper="0.5"/>

  <xacro:LINK name="arm0" width="0.2" depth="0.5" height="0.2" color="red">
    <origin xyz="0 0.15 1.5" rpy="0 0 0"/>
  </xacro:LINK>


  <xacro:macro name="LINK" params="name *origin width:=0.0 depth:=0.0 height:=0.0 color:=white">
    <link name="${name}">
      <visual>
        <xacro:insert_block name="origin"/>
        <geometry>
          <box size="${width} ${depth} ${height}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
    </link>
  </xacro:macro>

  <xacro:macro name="FIXED_JOINT" params="parent child">
    <joint name="${parent}->${child}" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="PRISMATIC_JOINT" params="parent child x:=0 y:=0 z:=0 lower upper">
    <joint name="${parent}->${child}" type="prismatic">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${x} ${y} ${z}"/>
      <limit lower="${lower}" upper="${upper}" effort="1.0" velocity="1.0"/>
    </joint>
  </xacro:macro>

</robot>
