<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="arcsys2">

  <material name="white"> <color rgba="${255/255} ${255/255} ${255/255} 1.0"/> </material>
  <material name="red">   <color rgba="${255/255} ${  0/255} ${  0/255} 1.0"/> </material>
  <material name="green"> <color rgba="${  0/255} ${255/255} ${  0/255} 1.0"/> </material>
  <material name="blue">  <color rgba="${  0/255} ${  0/255} ${255/255} 1.0"/> </material>


  <xacro:LINK name="world">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:LINK>

  <xacro:LIMITED_JOINT parent="world" child="shaft" type="prismatic" x="1" lower="-5.0" upper="5.0"/>

  <xacro:property name="shaft_thickness" value="0.1"/>
  <xacro:property name="shaft_height" value="2.0"/>
  <xacro:LINK name="shaft" width="${shaft_thickness}" depth="${shaft_thickness}" height="${shaft_height}" color="black">
    <origin xyz="0 0 ${shaft_height/2}" rpy="0 0 0"/>
  </xacro:LINK>

  <xacro:LIMITED_JOINT parent="shaft" child="arm0" type="prismatic" z="1" lower="-0.5" upper="0.5"/>

  <xacro:property name="arm_width" value="0.1"/>
  <xacro:property name="arm_depth" value="0.5"/>
  <xacro:property name="arm_height" value="${arm_width}"/>
  <xacro:LINK name="arm0" width="${arm_width}" depth="${arm_depth}" height="${arm_height}">
    <origin xyz="0 ${shaft_thickness} ${shaft_height*0.75}" rpy="0 0 0"/>
  </xacro:LINK>

  <xacro:property name="pi" value="3.1415"/>
  <xacro:LIMITED_JOINT parent="arm0" child="arm1" type="revolute" z="1" lower="${-pi}" upper="${pi}"/>

  <xacro:LINK name="arm1" width="${arm_width}" depth="${arm_depth}" height="${arm_height}" color="black">
    <origin xyz="0 ${shaft_thickness+arm_depth} ${shaft_height*0.75}" rpy="0 0 0"/>
  </xacro:LINK>


  <xacro:macro name="LINK" params="name *origin width:=0.0 depth:=0.0 height:=0.0 color:=white">
    <link name="${name}">
      <visual>
        <xacro:insert_block name="origin"/>
        <geometry>
          <box size="${width} ${depth} ${height}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
    </link>
  </xacro:macro>

  <!--xacro:macro name="FIXED_JOINT" params="parent child">
    <joint name="${parent}->${child}" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
    </joint>
  </xacro:macro-->

  <xacro:macro name="LIMITED_JOINT" params="parent child type x:=0 y:=0 z:=0 lower upper *origin">
    <joint name="${parent}->${child}" type="${type}">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${x} ${y} ${z}"/>
      <limit lower="${lower}" upper="${upper}" effort="1.0" velocity="1.0"/>
    </joint>
  </xacro:macro>

</robot>
