<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="arcsys2">

<!-- MATERIAL -->
  <material name="white"> <color rgba="${255/255} ${255/255} ${255/255} 1.0" /> </material>
  <material name="red">   <color rgba="${255/255} ${  0/255} ${  0/255} 1.0" /> </material>
  <material name="green"> <color rgba="${  0/255} ${255/255} ${  0/255} 1.0" /> </material>
  <material name="blue">  <color rgba="${  0/255} ${  0/255} ${255/255} 1.0" /> </material>


<!-- PROPERTY -->
  <xacro:property name="pi" value="3.1415926535897931" />

  <xacro:property name="default_size"     value="0.100" />
  <xacro:property name="default_lower"    value="${-pi/2}" />
  <xacro:property name="default_upper"    value="${+pi/2}" />
  <xacro:property name="default_effort"   value="1.000" />
  <xacro:property name="default_velocity" value="1.000" />

  <xacro:property name="arm_init"     value="0" />

  <xacro:property name="rail_depth"  value="${default_size}" />
  <xacro:property name="rail_width"  value="3.600" />
  <xacro:property name="rail_height" value="0.060" />

  <xacro:property name="base_depth"  value="0.580" />
  <xacro:property name="base_width"  value="0.750" />
  <xacro:property name="base_height" value="0.520" />

  <xacro:property name="shaft_offx"   value="-0.120" />
  <xacro:property name="shaft_offy"   value="0" />
  <xacro:property name="shaft_offz"   value="0" />
  <xacro:property name="shaft_depth"  value="${default_size}" />
  <xacro:property name="shaft_width"  value="${default_size}" />
  <xacro:property name="shaft_height" value="0.850" />

  <xacro:property name="arm0_depth"  value="0.125" />
  <xacro:property name="arm0_width"  value="${default_size}" />
  <xacro:property name="arm0_height" value="${default_size}" />

  <xacro:property name="arm1_depth"  value="0.216" />
  <xacro:property name="arm1_width"  value="${default_size}" />
  <xacro:property name="arm1_height" value="${default_size}" />

  <xacro:property name="arm2_depth"  value="0.199" />
  <xacro:property name="arm2_width"  value="${default_size}" />
  <xacro:property name="arm2_height" value="${default_size}" />

  <xacro:property name="effector_depth"  value="0.225" />
  <xacro:property name="effector_width"  value="${default_size}" />
  <xacro:property name="effector_height" value="${default_size}" />

  <xacro:property name="kinect_offx" value="-0.250" />
  <xacro:property name="kinect_offy" value="0.300" />
  <xacro:property name="kinect_offz" value="0.360" />

  <xacro:property name="kinect_depth"  value="${default_size}" />
  <xacro:property name="kinect_width"  value="${default_size}" />
  <xacro:property name="kinect_height" value="${default_size}" />


<!-- LINK AND JOINT -->
  <xacro:PLAIN_LINK name="rail" depth="${rail_depth}" width="${rail_width*2}" height="${rail_height}">
    <origin xyz="${rail_width} 0 0" />
  </xacro:PLAIN_LINK>

  <xacro:PRISMATIC_JOINT parent="rail" child="base" y="1" lower="0" upper="${rail_width-base_width/2}">
  <!-- <xacro:PRISMATIC_JOINT parent="rail" child="base" y="1" lower="${rail_width-base_width/2}" upper="0"> -->
    <origin xyz="0 0 ${base_height/2}" />
  </xacro:PRISMATIC_JOINT>

  <xacro:PLAIN_LINK name="base" depth="${base_depth}" width="${base_width}" height="${base_height}" color="red">
    <origin xyz="0 0 0" />
  </xacro:PLAIN_LINK>

  <xacro:FIXED_JOINT parent="base" child="kinect">
    <origin xyz="${kinect_offx} ${kinect_offy} ${kinect_offz+base_height/2}" />
  </xacro:FIXED_JOINT>

  <xacro:PLAIN_LINK name="kinect" depth="${kinect_depth}" width="${kinect_width}" height="${kinect_height}" color="green">
    <origin xyz="0 0 0" />
  </xacro:PLAIN_LINK>

  <xacro:FIXED_JOINT parent="base" child="shaft">
    <origin xyz="${shaft_offx} ${shaft_offy} ${shaft_offz+shaft_height/2}" />
  </xacro:FIXED_JOINT>

  <xacro:PLAIN_LINK name="shaft" depth="${shaft_depth}" width="${shaft_width}" height="${shaft_height}" color="blue">
    <origin xyz="0 0 0" />
  </xacro:PLAIN_LINK>

  <xacro:PRISMATIC_JOINT parent="shaft" child="arm0" z="1" lower="0" upper="0.30">
    <origin xyz="${shaft_depth/2} 0 ${arm_init}" />
  </xacro:PRISMATIC_JOINT>

  <xacro:SCARA_LINK name="arm0" depth="${arm0_depth}" width="${arm0_width}" height="${arm0_height}" color="red" />

  <xacro:REVOLUTE_JOINT parent="arm0" child="arm1" axisz="1">
    <origin xyz="${arm0_depth} 0 0" />
  </xacro:REVOLUTE_JOINT>

  <xacro:SCARA_LINK name="arm1" depth="${arm1_depth}" width="${arm1_width}" height="${arm1_height}" color="green" />

  <xacro:REVOLUTE_JOINT parent="arm1" child="arm2" axisz="1">
    <origin xyz="${arm1_depth} 0 0" />
  </xacro:REVOLUTE_JOINT>

  <xacro:SCARA_LINK name="arm2" depth="${arm2_depth}" width="${arm2_width}" height="${arm2_height}" color="blue" />

  <xacro:REVOLUTE_JOINT parent="arm2" child="effector" axisz="1">
    <origin xyz="${arm2_depth} 0 0" />
  </xacro:REVOLUTE_JOINT>

  <xacro:SCARA_LINK name="effector" depth="${effector_depth/2}" width="${effector_width}" height="${effector_height}" color="red" />

  <xacro:REVOLUTE_JOINT parent="effector" child="blade" axisx="1" lower="0" upper="${pi*3/4}">
    <origin xyz="${effector_depth/2} 0 0" />
  </xacro:REVOLUTE_JOINT>

  <xacro:SCARA_LINK name="blade" depth="${effector_depth/2}" width="${effector_width}" height="${effector_height}" color="red" />


<!-- MACRO DEFINITION -->
  <xacro:macro name="PLAIN_LINK" params="name *origin width:=${default_size} depth:=${default_size} height:=${default_size} color:=white">
    <link name="${name}">
      <xacro:insert_block name="origin" />
      <visual>
        <geometry> <box size="${depth} ${width} ${height}" /> </geometry>
        <material name="${color}" />
      </visual>
    </link>
  </xacro:macro>

  <xacro:macro name="SCARA_LINK" params="name width:=${default_size} depth:=${default_size} height:=${default_size} offy:=0 offz:=0 color:=white">
    <link name="${name}">
      <visual>
        <origin xyz="${depth/2} ${offy} ${offz}" />
        <geometry> <box size="${depth} ${width} ${height}" /> </geometry>
        <material name="${color}" />
      </visual>
    </link>
  </xacro:macro>

  <xacro:macro name="FIXED_JOINT" params="parent child *origin">
    <joint name="${parent}_to_${child}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${child}" />
    </joint>
  </xacro:macro>

  <xacro:macro name="PRISMATIC_JOINT" params="parent child x:=0 y:=0 z:=0 lower:=-1 upper:=1 *origin">
    <joint name="${parent}_to_${child}_joint" type="prismatic">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${x} ${y} ${z}"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="REVOLUTE_JOINT" params="parent child *origin axisx:=0 axisy:=0 axisz:=0 lower:=${default_lower} upper:=${default_upper} effort:=${default_effort} velocity:=${default_velocity}">
    <joint name="${parent}_to_${child}_joint" type="revolute">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${child}" />
      <axis xyz="${axisx} ${axisy} ${axisz}" />
      <limit lower="${lower}" upper="${upper}" effort="${effort}" velocity="${velocity}" />
    </joint>
  </xacro:macro>

</robot>
