<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="arcsys2">

  <material name="white"> <color rgba="${255/255} ${255/255} ${255/255} 1.0" /> </material>
  <material name="red">   <color rgba="${255/255} ${  0/255} ${  0/255} 1.0" /> </material>
  <material name="green"> <color rgba="${  0/255} ${255/255} ${  0/255} 1.0" /> </material>
  <material name="blue">  <color rgba="${  0/255} ${  0/255} ${255/255} 1.0" /> </material>


<!-- Property -->
  <xacro:property name="pi" value="3.1415926535897931" />
  <xacro:property name="default_size" value="0.1"/>

  <xacro:property name="rail_length"     value="10.0" />
  <xacro:property name="shaft_height"    value="2.0"/>
  <xacro:property name="arm0_length"     value="0.1"/>
  <xacro:property name="arm1_length"     value="0.5"/>
  <xacro:property name="arm2_length"     value="0.5"/>
  <xacro:property name="effector_length" value="0.5"/>

  <xacro:property name="default_hardware_interface"
                 value="hardware_interface/PositionJointInterface" />

<!-- LINK and JOINT -->
  <xacro:PLAIN_LINK width="${rail_length}" name="rail"/>

  <xacro:PRISMATIC_JOINT parent="rail" child="shaft" y="1" lower="${-1*rail_length/2}" upper="${rail_length/2}">
    <origin xyz="0 0 ${shaft_height/2}"/>
  </xacro:PRISMATIC_JOINT>

  <xacro:PLAIN_LINK name="shaft" height="${shaft_height}" color="red"/>

  <xacro:PRISMATIC_JOINT parent="shaft" child="arm0" z="1" lower="-0.5" upper="0.5">
    <origin xyz="${default_size/2} 0 ${shaft_height/4}"/>
  </xacro:PRISMATIC_JOINT>

  <xacro:SCARA_LINK name="arm0" length="${arm0_length}" color="green"/>

  <xacro:SCARA_JOINT parent="arm0" child="arm1" parent_length="${arm0_length}"/>

  <xacro:SCARA_LINK name="arm1" length="${arm1_length}" color="blue"/>

  <xacro:SCARA_JOINT parent="arm1" child="arm2" parent_length="${arm1_length}"/>

  <xacro:SCARA_LINK name="arm2" length="${arm2_length}" color="red"/>

  <xacro:SCARA_JOINT parent="arm2" child="effector_base" parent_length="${arm2_length}"/>

  <xacro:SCARA_LINK name="effector_base" length="${effector_length/2}" color="green"/>

  <xacro:WRIST_JOINT parent="effector_base" child="effector_end" parent_length="${effector_length/2}" />

  <xacro:SCARA_LINK name="effector_end" length="${effector_length/2}" color="blue" />


<!-- Macro Definition -->
  <xacro:macro name="PLAIN_LINK" params="name width:=${default_size} length:=${default_size} height:=${default_size} color:=white">
    <link name="${name}">
      <origin xyz="0 0 0"/>
      <visual>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="SCARA_LINK" params="name width:=${default_size} length:=${default_size} height:=${default_size} color:=white">
    <link name="${name}">
      <visual>
        <origin xyz="${length/2} 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="FIXED_JOINT" params="parent child *origin">
    <joint name="${parent}_to_${child}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="PRISMATIC_JOINT" params="parent child x:=0 y:=0 z:=0 lower:=${-pi/2} upper:=${pi/2} *origin reduction:=1.0 hardware_interface:=${default_hardware_interface}">
    <joint name="${parent}_to_${child}_joint" type="prismatic">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${x} ${y} ${z}"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>

    <transmission name="${parent}_to_${child}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${parent}_to_${child}_actuator">
        <mechanicalReduction>${reduction}</mechanicalReduction>
        <hardwareInterface>${default_hardware_interface}</hardwareInterface>
      </actuator>
      <joint name="${parent}_to_${child}_joint">
        <hardwareInterface>${default_hardware_interface}</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

  <xacro:macro name="SCARA_JOINT" params="parent child parent_length lower:=${-pi/2} upper:=${pi/2} reduction:=1.0 hardware_interface:=${default_hardware_interface}">
    <joint name="${parent}_to_${child}_joint" type="revolute">
      <origin xyz="${parent_length} 0 0"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>

    <transmission name="${parent}_to_${child}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${parent}_to_${child}_actuator">
        <mechanicalReduction>${reduction}</mechanicalReduction>
        <hardwareInterface>${default_hardware_interface}</hardwareInterface>
      </actuator>
      <joint name="${parent}_to_${child}_joint">
        <hardwareInterface>${default_hardware_interface}</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

  <xacro:macro name="WRIST_JOINT" params="parent child parent_length lower:=${-pi/2} upper:=${pi/2} reduction:=1.0 hardware_interface:=${default_hardware_interface}">
    <joint name="${parent}_to_${child}_joint" type="revolute">
      <origin xyz="${parent_length} 0 0"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="1 0 0"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>

    <transmission name="${parent}_to_${child}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${parent}_to_${child}_actuator">
        <mechanicalReduction>${reduction}</mechanicalReduction>
        <hardwareInterface>${default_hardware_interface}</hardwareInterface>
      </actuator>
      <joint name="${parent}_to_${child}_joint">
        <hardwareInterface>${default_hardware_interface}</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

</robot>
