<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="arcsys2">

  <material name="white"> <color rgba="${255/255} ${255/255} ${255/255} 1.0" /> </material>
  <material name="red">   <color rgba="${255/255} ${  0/255} ${  0/255} 1.0" /> </material>
  <material name="green"> <color rgba="${  0/255} ${255/255} ${  0/255} 1.0" /> </material>
  <material name="blue">  <color rgba="${  0/255} ${  0/255} ${255/255} 1.0" /> </material>



  <xacro:property name="pi" value="3.1415926535897931" />

  <xacro:property name="default_size" value="0.100" />
  <xacro:property name="arm_init" value="0.200" />

  <xacro:property name="rail_depth"  value="${default_size}" />
  <xacro:property name="rail_width"  value="3.600" />
  <xacro:property name="rail_height" value="${default_size}" />

  <xacro:property name="base_depth"  value="1.000" />
  <xacro:property name="base_width"  value="0.850" />
  <xacro:property name="base_height" value="1.000" />

  <xacro:property name="shaft_depth"  value="${default_size}" />
  <xacro:property name="shaft_width"  value="${default_size}" />
  <xacro:property name="shaft_height" value="1.000" />

  <xacro:property name="arm0_depth"  value="0.125" />
  <xacro:property name="arm0_width"  value="${default_size}" />
  <xacro:property name="arm0_height" value="${default_size}" />

  <xacro:property name="arm1_depth"  value="0.216" />
  <xacro:property name="arm1_width"  value="${default_size}" />
  <xacro:property name="arm1_height" value="${default_size}" />

  <xacro:property name="arm2_depth"  value="0.199" />
  <xacro:property name="arm2_width"  value="${default_size}" />
  <xacro:property name="arm2_height" value="${default_size}" />

  <xacro:property name="effector_depth"  value="0.225" />
  <xacro:property name="effector_width"  value="${default_size}" />
  <xacro:property name="effector_height" value="${default_size}" />

  <xacro:property name="kinect_offset_x" value="${default_size}" />
  <xacro:property name="kinect_offset_y" value="0.265" />
  <xacro:property name="kinect_offset_z" value="${default_size}" />

  <xacro:property name="kinect_depth"  value="${default_size}" />
  <xacro:property name="kinect_width"  value="${default_size}" />
  <xacro:property name="kinect_height" value="${default_size}" />



  <xacro:PLAIN_LINK name="rail" depth="${rail_depth}" width="${rail_width}" height="${rail_height}" />

  <xacro:PRISMATIC_JOINT parent="rail" child="base" y="1" lower="${-1*rail_width}" upper="${rail_width}">
    <origin xyz="0 0 ${base_height/2}" />
  </xacro:PRISMATIC_JOINT>

  <xacro:PLAIN_LINK name="base" depth="${base_depth}" width="${base_width}" height="${base_height}" />

  <xacro:FIXED_JOINT parent="base" child="kinect">
    <origin xyz="${kinect_offset_x} ${kinect_offset_y} ${kinect_offset_z}" />
  </xacro:FIXED_JOINT>

  <xacro:PLAIN_LINK name="kinect" depth="${kinect_depth}" width="${kinect_width}" height="${kinect_height}" />

  <xacro:FIXED_JOINT parent="base" child="shaft">
    <origin xyz="0 0 ${shaft_height/2}" />
  </xacro:FIXED_JOINT>

  <xacro:PLAIN_LINK name="shaft" depth="${shaft_depth}" width="${shaft_width}" height="${shaft_height}" />

  <xacro:PRISMATIC_JOINT parent="shaft" child="arm0" z="1" lower="${-default_size}" upper="${default_size}">
    <origin xyz="${shaft_depth/2} 0 ${arm_init}" />
  </xacro:PRISMATIC_JOINT>

  <xacro:SCARA_LINK name="arm0" depth="${arm0_depth}" width="${arm0_width}" height="${arm0_height}" />
  <xacro:SCARA_JOINT parent="arm0" child="arm1" parent_depth="${arm0_depth}" />
  <xacro:SCARA_LINK name="arm1" depth="${arm1_depth}" width="${arm1_width}" height="${arm1_height}" />
  <xacro:SCARA_JOINT parent="arm1" child="arm2" parent_depth="${arm1_depth}" />
  <xacro:SCARA_LINK name="arm2" depth="${arm2_depth}" width="${arm2_width}" height="${arm2_height}" />
  <xacro:SCARA_JOINT parent="arm2" child="effector" parent_depth="${arm2_depth}" />
  <xacro:SCARA_LINK name="effector" depth="${effector_depth/2}" width="${effector_width}" height="${effector_height}" />
  <xacro:WRIST_JOINT parent="effector" child="blade" parent_depth="${effector_depth/2}" />
  <xacro:SCARA_LINK name="blade" depth="${effector_depth/2}" width="${effector_width}" height="${effector_height}" />



  <xacro:macro name="PLAIN_LINK" params="name width:=${default_size} depth:=${default_size} height:=${default_size} color:=white">
    <link name="${name}">
      <origin xyz="0 0 0"/>
      <visual>
        <geometry> <box size="${depth} ${width} ${height}"/> </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <geometry> <box size="${depth} ${width} ${height}"/> </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="SCARA_LINK" params="name width:=${default_size} depth:=${default_size} height:=${default_size} color:=white">
    <link name="${name}">
      <visual>
        <origin xyz="${depth/2} 0 0"/>
        <geometry> <box size="${depth} ${width} ${height}"/> </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <geometry> <box size="${depth} ${width} ${height}"/> </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="FIXED_JOINT" params="parent child *origin">
    <joint name="${parent}_to_${child}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="PRISMATIC_JOINT" params="parent child x:=0 y:=0 z:=0 lower:=-1 upper:=1 *origin">
    <joint name="${parent}_to_${child}_joint" type="prismatic">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${x} ${y} ${z}"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="SCARA_JOINT" params="parent child parent_depth lower:=${-pi/2} upper:=${pi/2}">
    <joint name="${parent}_to_${child}_joint" type="revolute">
      <origin xyz="${parent_depth} 0 0"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="WRIST_JOINT" params="parent child parent_depth lower:=${-pi/2} upper:=${pi/2}">
    <joint name="${parent}_to_${child}_joint" type="revolute">
      <origin xyz="${parent_depth} 0 0"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="1 0 0"/>
      <limit lower="${lower}" upper="${upper}" effort="1" velocity="1"/>
    </joint>
  </xacro:macro>
</robot>
