controller_list:
  - name: fake_arcsys2_controller
    joints:
      - rail_to_shaft
      - shaft_to_arm0
      - arm0_to_arm1
      - arm1_to_arm2
      - arm2_to_effector_base
      - effector_base_to_effector_end