arcsys2_position_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - rail_to_base_joint
    - shaft_to_arm0_joint
    - arm0_to_arm1_joint
    - arm1_to_arm2_joint
    - arm2_to_effector_joint
    - effector_to_blade_joint
