arcsys2:
  joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - rail_to_shaft_joint
      - shaft_to_arm0_joint
      - arm0_to_arm1_joint
      - arm1_to_arm2_joint
      - arm2_to_effector_base_joint
      - effector_base_to_effector_end_joint
